POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.google.com/search?q=slack+how+to+see+archived+channels&oq=slack+how+to+see+arch&aqs=chrome.0.0i512j69i57j0i22i30j0i390l4.3929j0j7&sourceid=chrome&ie=UTF-8"
}